### ISSUE TITLE
Contributing guidelines are missing

### ISSUE THREAD

**Issue by drj11** [TNanukem/scikit-net#37]
The JOSS review checklist asks that:

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

Because the project is hosted on GitHub it is at least implicitly clear that opening an issue can be used for 2) and 3).

There are no guidelines for how to contribute to the software (or, if there are, they are not made clear).

I would suggest a `contributing.md` file, which could also cover 2) and 3) more explicitly.

This is blocking review, I won't check the JOSS review checkbox until this is resolved.

**Comment by imw** [comment]
@drj11 Do you think the [development](https://tnanukem.github.io/scikit-net/main/development/index.html) page of the docs is sufficient? Or would you like to see this reflected in the code itself?

**Comment by drj11** [comment]
aha, i didn't actually find that. I still think a `contributing.md` would be a good idea. Either with a brief summary and a link to that page, or the text of that page.

If you create a `contributing.md` GitHub creates a prompt and link when you open a new issue. It's a becoming a standard practice.
