### ISSUE TITLE
Minor copy edits

### ISSUE THREAD

**Issue by imw** [TNanukem/scikit-net#40]
There are a handful of minor grammatical issues in the JOSS paper. Rather than list them here, it seemed easier to open a PR:
https://github.com/TNanukem/scikit-net/compare/docs/joss_paper...imw:patch-1

**Comment by drj11** [comment]
You should press "Create Pull Request" on the page at that link. You haven't actually created the PR yet, but you do seem to have created a branch and a commit on it.

**Comment by TNanukem** [comment]
I created the pull request and merged it on the branch. Thank you!
