### ISSUE TITLE
Network building models are lacking!

### ISSUE THREAD

**Issue by KONEONE** [TNanukem/scikit-net#47]
Hello, when I read the source code of the dataset_constructor module, I found that the network construction model currently supported by sknet is very limited. I would like to ask, do you currently have a follow-up development plan?

**Comment by TNanukem** [comment]
Hello.

I plan on keep developing the library, however, since I do it alone, it may take a while for new updates to come up.

Any help to do so would be appreciated.

That being said, do you have any suggestions of methods you would like to see implemented?

**Comment by KONEONE** [comment]
Sorry, I can't give any suggestions at present. Because I am still a novice in complex network. I have only been in the field of complex networks for a week. Use your library to quickly verify your ideas. Thank you very much for building this library.
